### ISSUE TITLE
Exception on host_name

### ISSUE THREAD

**Issue by mohierf** [savoirfairelinux/mod-influxdb#24]
I had a problem after a bad restart of my Shinken and as a side effect I got many exceptions in the module : 
```
[1432292887] WARNING: [broker-master] Back trace of this kill: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/daemons/brokerdaemon.py", line 276, in manage_brok
    mod.manage_brok(b)
  File "/usr/local/lib/python2.7/site-packages/Shinken-2.4_rc4-py2.7.egg/shinken/basemodule.py", line 243, in manage_brok
    return manage(brok)
  File "/usr/local/libexec/shinken/modules/mod-influxdb/module.py", line 215, in manage_host_check_result_brok
    "address": self.host_config[host_name]['address'],
KeyError: u'lachassagne'
```

**Comment by mohierf** [comment]
In my own modules, I also implemented a dictionary containing hosts names.

When receiving initial host state brok : 
```
            host_name = b.data['host_name']

            try:
                logger.debug("[glpidb] initial host status : %s : %s", host_name, b.data['customs'])
                self.hosts_cache[host_name] = {'hostsid': b.data['customs']['_HOSTID'], 'itemtype': b.data['customs']['_ITEMTYPE'], 'items_id': b.data['customs']['_ITEMSID'] }
            except:
                self.hosts_cache[host_name] = {'items_id': None}
```

and then on receiving host state brok:
```
            host_name = b.data['host_name']
            
            if host_name in self.hosts_cache and self.hosts_cache[host_name]['items_id'] is not None:
                start = time.time()
                self.record_host_check_result(b)
                logger.debug("[glpidb] host check result: %s, %d seconds", host_name, time.time() - start)
```

In this way you protect against not receiving initial hosts states ... because it happens sometimes :/P !

**Comment by mohierf** [comment]
Not sure I have your last version of the module ...

**Comment by aviau** [comment]
This shouldn't happen in the last version

**Comment by mohierf** [comment]
Available with *shinken install* or should I update module file ?

**Comment by aviau** [comment]
It is available with ``shinken install``

**Comment by mohierf** [comment]
Thanks. I installed on my testing environment and it seems ok now.
